In [1]:
import numpy as np

In [2]:
arr = []

In [3]:
arr

[]

In [5]:
arr.append(5)

In [6]:
arr

[5]

In [7]:
len(arr)

1

In [8]:
arr2d = np.array([[1,2], [3,4]])
arr2d

array([[1, 2],
       [3, 4]])

In [9]:
arr2d[1,1]

4

In [12]:
arr

[5]

In [13]:
np.array(arr)

array([5])

In [14]:
arr[0]

5

In [15]:
v = np.array([[1, 4, 0, 0, 1],
 [0, 0, 0, 0, 0],
 [0, 5, 6, 0, 0],
 [0, 0, 3, 0, 0]])

In [21]:
v[v[0]]

IndexError: index 4 is out of bounds for axis 0 with size 4

In [22]:
for i in v:
    print(i)

[1 4 0 0 1]
[0 0 0 0 0]
[0 5 6 0 0]
[0 0 3 0 0]


In [24]:
# for(int i=0; i < v.length; i++)
for i in range(len(v)):
    for j in range(len(v[i])):
        print(str(i) + "," + str(j))

0,0
0,1
0,2
0,3
0,4
1,0
1,1
1,2
1,3
1,4
2,0
2,1
2,2
2,3
2,4
3,0
3,1
3,2
3,3
3,4


In [17]:
for i in v:
    for j in v[i]:
        print(j)

1
4
0
0
1
0
0
0
0
0
0
5
6
0
0
0
0
3
0
0
